import crypto from 'node:crypto';
const secret=()=>process.env.TOKEN_SECRET||'';const adminId=()=>process.env.ADMIN_ID||'Admingod';
const sb=()=>({url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY});
async function db(path,opts={}){const x=sb();if(!x.url||!x.key)throw Error('ยังไม่ได้ตั้งค่า Supabase');const h={'apikey':x.key,'Authorization':'Bearer '+x.key,'Content-Type':'application/json',...(opts.headers||{})};const r=await fetch(x.url+'/rest/v1/'+path,{...opts,headers:h});if(r.status===204)return null;const t=await r.text();if(!r.ok)throw Error(t||`Supabase HTTP ${r.status}`);return t?JSON.parse(t):null}
const b64=x=>Buffer.from(x).toString('base64url');const now=()=>new Date().toISOString();const pub=u=>({id:u.id,role:u.role,active:!!u.active,createdAt:u.created_at,expiresAt:u.expires_at||null});
function hash(p,s=crypto.randomBytes(16).toString('hex')){return {salt:s,hash:crypto.scryptSync(p,s,64).toString('base64url')}}function verify(p,u){try{return crypto.timingSafeEqual(crypto.scryptSync(p,u.password_salt,64),Buffer.from(u.password_hash,'base64url'))}catch{return false}}
function expired(u){return u.expires_at&&Date.parse(u.expires_at)<=Date.now()}
function sign(p){return b64(crypto.createHmac('sha256',secret()).update(p).digest())}function makeToken(u){const p=b64(JSON.stringify({sub:u.id,role:u.role,pv:u.password_version,exp:Date.now()+43200000}));return p+'.'+sign(p)}
async function auth(req){if(!secret()||secret().length<32)return null;const [p,s]=(req.headers.authorization||'').replace('/api/','/');try{const x=JSON.parse(Buffer.from(p,'base64url').toString()),a=await db(`users?id=eq.${encodeURIComponent(x.sub)}&select=*`);const u=a?.[0];return u&&u.active&&!expired(u)&&u.password_version===x.pv&&x.exp>Date.now()?u:null}catch{return null}}
function out(res,status,data){res.status(status).setHeader('Cache-Control','no-store');res.setHeader('Access-Control-Allow-Origin',process.env.CORS_ORIGIN||'*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');return res.json(data)}
export default async function handler(req,res){if(req.method==='OPTIONS')return out(res,204,{});const path=new URL(req.url,'https://vercel.local').pathname.replace('/api','');try{if(req.method==='GET'&&path==='/health')return out(res,200,{ok:true,service:'Kheitai Membership API',time:now()});if(req.method==='POST'&&path==='/login'){const {id='',password=''}=req.body||{},a=await db(`users?id=eq.${encodeURIComponent(String(id).trim())}&select=*`),u=a?.[0];if(!u||!u.active||expired(u)||!verify(String(password),u))return out(res,401,{error:'ไอดีหรือรหัสผ่านไม่ถูกต้อง หรือสมาชิกหมดอายุ/ถูกปิดใช้งาน'});return out(res,200,{token:makeToken(u),user:pub(u)})}const u=await auth(req);if(!u)return out(res,401,{error:'เซสชันหมดอายุหรือสมาชิกถูกปิดใช้งาน กรุณาเข้าสู่ระบบใหม่'});if(req.method==='GET'&&path==='/me')return out(res,200,{user:pub(u)});if(u.role!=='admin')return out(res,403,{error:'เฉพาะ AdminGod เท่านั้น'});if(req.method==='GET'&&path==='/admin/members'){const a=await db('users?role=neq.admin&select=*&order=created_at.desc');return out(res,200,{members:a.map(pub)})}if(req.method==='POST'&&path==='/admin/members'){const b=req.body||{},id=String(b.id||'').trim(),pw=String(b.password||'');if(!/^[A-Za-z0-9_.-]{3,40}$/.test(id)||pw.length<8)return out(res,400,{error:'ไอดีหรือรหัสผ่านไม่ถูกต้อง'});const h=hash(pw),ex=b.expiresAt?new Date(b.expiresAt).toISOString():null;await db('users',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id,password_hash:h.hash,password_salt:h.salt,role:'member',expires_at:ex,active:true,password_version:1})});return out(res,201,{ok:true})}const m=path.match(/^\/admin\/members\/([^/]+)$/);if(m){const id=decodeURIComponent(m[1]);if(id===adminId())return out(res,400,{error:'ไม่อนุญาตให้แก้ไข AdminGod'});if(req.method==='DELETE'){await db(`users?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});return out(res,200,{ok:true})}if(req.method==='PATCH'){const b=req.body||{},v={};if(b.password!==undefined){if(String(b.password).length<8)return out(res,400,{error:'รหัสผ่านต้องยาวอย่างน้อย 8 ตัวอักษร'});const h=hash(String(b.password));Object.assign(v,{password_hash:h.hash,password_salt:h.salt,password_version:undefined})}if(b.active!==undefined)v.active=!!b.active;if(b.expiresAt!==undefined)v.expires_at=b.expiresAt?new Date(b.expiresAt).toISOString():null;await db(`users?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(v)});if(v.password_hash)await db(`users?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({password_version: (await db(`users?id=eq.${encodeURIComponent(id)}&select=password_version`))[0].password_version+1})});return out(res,200,{ok:true})}}return out(res,404,{error:'ไม่พบ endpoint'})}catch(e){console.error(e);return out(res,400,{error:e.message||'คำขอไม่ถูกต้อง'})}}
